name: syncToGitee
on:
  push:
    branches:
      - main
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/Jhonson1z'
          dst: 'gitee/INeedAGodDamnGUN'
          dst_key: ${{ secrets.GITEE_ACTIONS_KEY }}
          dst_token:  ${{ secrets.GITEE_KEY }}
          static_list: "notebook"
          force_update: true
			    debug: true